version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/actions
    overwrite: yes

permissions:
  - object: /home/ec2-user/actions
    owner: ec2-user
    group: ec2-user
    pattern: "**"
    mode: 755

hooks:
  ApplicationStart:
    - location: /scripts/deploy.sh
      timeout: 60
      runas: ec2-user